TEST3

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -20,18 +20,29 @@ jobs:
 
       - name: Terraform Init
         run: terraform init
+        
+        - name: Validate Azure credentials exist
+  run: |
+    for v in ARM_CLIENT_ID ARM_CLIENT_SECRET ARM_TENANT_ID; do
+      if [ -z "${!v}" ]; then
+        echo "$v is missing ❌"
+        exit 1
+      fi
+    done
+    echo "All Azure credentials present ✅"
+
 
       - name: Terraform Plan
         run: terraform plan
         env:
-          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
+          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
+          ARM_CLIENT_SECRET: ${{ vars.AZURE_CLIENT_SECRET }}
 
       - name: Terraform Apply
         if: github.ref == 'refs/heads/class'
         run: terraform apply -auto-approve
         env:
-          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
+          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
+          ARM_CLIENT_SECRET: ${{ vars.AZURE_CLIENT_SECRET }}
